branches:
  only: master

language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_API=27
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=27.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$EMULATOR_API

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - android list targets
  - echo no |  android create avd --force -n test -t "android-"$EMULATOR_API --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - cd SuperHero
  - "./gradlew clean check connectedCheck"

